import type { Metadata } from "next";
import { Toaster } from 'react-hot-toast';
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LLM-Chat-WebUI",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} background min-h-screen h-screen overflow-hidden`}>
        <Provider>
          <Toaster position="top-right" />
          {children}
        </Provider>
      </body>
    </html>
  );
}
